spring:
  application:
    name: local-grpc-server
server:
  port: 8080
grpc:
  port: 8090
  enable-reflection: true
const:
  outputPath: file:/C:/lab-rating-system-student-server/src/main/resources/output
